package br.com.softplan.scpbackend.enums;

public enum Mensagens {

	MSG_PESSOA_CPF_NAO_PREENCHIDO,
	MSG_PESSOA_NOME_NAO_PREENCHIDO,
	MSG_PESSOA_CPF_INVALIDO, 
	MSG_PESSOA_DATANASCIMENTO_INVALIDA, 
	MSG_PESSOA_ERRO_INCLUIR,
	MSG_PESSOA_CPF_JA_CADASTRADO, 
	MSG_PESSOA_NAO_ENCONTRADA, 
	MSG_PESSOA_ERRO_ALTERAR;
	
	public String getProperty() {
		return "";
	}
	
}
